### ISSUE TITLE
トップ画面ボタンにリップルエフェクト

### ISSUE THREAD

**Issue by ikemura23** [banbara23/Yaeyama-Liner-Checker#1]
これを使いたい
http://qiita.com/konifar/items/d785618154371f10a510

**Comment by ikemura23** [comment]
こんな感じにするかも
![イメージ](http://forums.androidcentral.com/attachments/beta-requests/183455d1435202406t-free-app-airmore-web-based-application-manage-your-android-airmore.jpg)

**Comment by ikemura23** [comment]
しんぷる
![サンプル](http://images.wondershare.com/data-recovery/flash-drive/319.jpg)

**Comment by ikemura23** [comment]
このライブラリを使う
https://github.com/traex/RippleEffect

**Comment by banbara23** [comment]
運行状況のボタンと時刻表の間をもっと広げてみてはどうか。

-----------------------------
運行状況
[安永観光]  [八重山観光フェリー]


[時刻表]

[アプリ情報]

-----------------------------
