### ISSUE TITLE
Firebaseアナリティクス導入

### ISSUE THREAD

**Issue by ikemura23** [banbara23/Yaeyama-Liner-Checker#119]
Firebaseのアナリティクス

[FirebaseのcrashとanalyticsをAndroidアプリで試してみる - Qiita](http://qiita.com/yamacraft/items/fd736203c29dfd3c7050)

公式
https://github.com/firebase/quickstart-android/blob/master/analytics/app/src/main/java/com/google/firebase/quickstart/analytics/MainActivity.java

**Comment by banbara23** [comment]
Firebaseのアナリティクスに変更する
[FirebaseのcrashとanalyticsをAndroidアプリで試してみる - Qiita](http://qiita.com/yamacraft/items/fd736203c29dfd3c7050)
