### ISSUE TITLE
アプリトップのレイアウトをリニューアル

### ISSUE THREAD

**Issue by ikemura23** [banbara23/Yaeyama-Liner-Checker#43]
参考１
https://lh6.ggpht.com/1G7BuJiLhwiZpV7NPH9I3k3RNk_tdPU61qdYFrYETLrDkiPk18WCidQ4Yl4Eybshb0Ms=h900
参考２（１と似ている）
![](http://octoba.jp/wp-content/uploads/2015/03/com.navitime.local_.navitime_00-2.png)

**Comment by banbara23** [comment]
![](http://41.media.tumblr.com/712383274b1dc3c87566e38e3402c8ee/tumblr_nim6rvPM0J1r2wjwko6_1280.png)

**Comment by ikemura23** [comment]
![](http://41.media.tumblr.com/b371e3b9907d61be81217a01d6f8ed02/tumblr_n6kesjwOck1r2wjwko2_1280.png)

**Comment by ikemura23** [comment]
![inbox-3up 0](https://cloud.githubusercontent.com/assets/8417910/12372546/c01aefc4-bc9f-11e5-9b06-66135c1ae813.png)

**Comment by ikemura23** [comment]
![](http://blog.lemberg.co.uk/sites/blog/files/imce/email_v2.png)

**Comment by ikemura23** [comment]
![](http://img.wonderhowto.com/img/98/60/63564482210088/0/manage-app-permissions-android-no-root-required.w654.jpg)
