### ISSUE TITLE
時刻表のリニューアル

### ISSUE THREAD

**Issue by ikemura23** [banbara23/Yaeyama-Liner-Checker#46]
イメージ画像１
![](https://wearebase.com/wp-content/uploads/2014/06/nct-timetable-app.png)

**Comment by banbara23** [comment]
おしゃれ

![](http://assets.materialup.com/uploads/a0fa0902-9444-42c5-ae89-96a471bee4ac/shot1.png)

https://dribbble.com/shots/2292114-Productivity-Android-App

**Comment by ikemura23** [comment]
おしゃれ

![shot1](https://cloud.githubusercontent.com/assets/8417910/12281704/a7f2c23a-b9db-11e5-9d36-cd01ebf10cac.png)

https://dribbble.com/shots/2292114-Productivity-Android-App

**Comment by ikemura23** [comment]
[覚えておくと便利なデザイン関連のチップス - Qiita](http://qiita.com/suzukihr/items/e1c0791e8047d5a7e165#view-%E3%81%AE%E5%88%87%E3%82%8A%E6%9B%BF%E3%81%88%E3%82%92-viewanimator-%E3%81%A7%E8%A1%8C%E3%81%86)
ViewAnimatorがviewの切り替えによさげ

**Comment by ikemura23** [comment]
![default](https://cloud.githubusercontent.com/assets/8417910/12950611/6368ba70-d051-11e5-902f-2d32b94417c3.png)
