### ISSUE TITLE
トップ画面をダッシュボード化

### ISSUE THREAD

**Issue by ikemura23** [banbara23/Yaeyama-Liner-Checker#84]
トップ画面に簡易運行状況をダッシュボード的に表示したい

**Comment by banbara23** [comment]
[](http://cdn.speckyboy.com/wp-content/uploads/2016/01/mobile-app-free-ui-kit-template-06.png)

**Comment by banbara23** [comment]
![](http://assets.materialup.com/uploads/ecdd0861-ad8b-46c5-a18f-a0fda8c52533/preview.jpg)

**Comment by ikemura23** [comment]
![preview](https://cloud.githubusercontent.com/assets/8417910/12877142/cc9380ae-ce51-11e5-9869-a792110bc0d2.jpg)

**Comment by ikemura23** [comment]
TOP画面に出す表示イメージ

```
安栄観光：全航路 通常運航
八重山観光フェリー：欠航１
ドリーム観光：欠航１ 未定2
```

```
安栄観光         ○：5　X：0　△：0
八重山観光フェリー ○：5　X：2　△：1
ドリーム観光　　　 ○：5　X：2　△：1
```

**Comment by ikemura23** [comment]
東京メトロを参考
http://www.tokyometro.jp/unkou/history/ginza.html

![20160530-154518](https://cloud.githubusercontent.com/assets/8417910/15641718/90e3bd88-267d-11e6-97a8-b8b5ef1e9521.png)
![20160530-155606](https://cloud.githubusercontent.com/assets/8417910/15641940/1afc696a-267f-11e6-87e3-99dee93494e0.png)

**Comment by ikemura23** [comment]
entity構成

```
TopLinerStatuses
- TopLinerStatuses<TopLinerStatus>

TopLinerStatus
- Port
- Status
```

**Comment by ikemura23** [comment]
![2](https://cloud.githubusercontent.com/assets/8417910/15798963/7145f956-2a87-11e6-8163-93525d28c3ed.png)

**Comment by ikemura23** [comment]
船のデザインが強すぎて周りから浮いてるので、一旦非表示
吹き出しは #120 で実装する予定なので、ここでは触ってない

**Comment by ikemura23** [comment]
実装完了したのでクローズ
